Controllers/TravelPackageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp_travel_agency.Models;

namespace webapp_travel_agency.Controllers;


[Authorize]
public class TravelPackageController : Controller
{
    public IActionResult Index()
    {
        List<TravelPackage> travelPackages;

        using (TravelContext db = new TravelContext())
        {
            travelPackages = db.Travels.ToList();
        }

        return View("Index", travelPackages);
    }

    public IActionResult Show(int id)
    {
        TravelMessages travelMessages = new TravelMessages();
        
        travelMessages.TravelPackage = new TravelContext().Travels
            .Where(travelPackage => travelPackage.Id == id).First();
        
        travelMessages.Messages = new TravelContext().Messages
            .Where(message => message.TravelPackageId == id).ToList();
        
        if (travelMessages.TravelPackage  == null)
        {
            return NotFound($"Il viaggio con id {id} non è stato trovato");
        }
        else
        {
            return View("Show", travelMessages);
        }
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View("Create");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(TravelPackage formData)
    {
        if (!ModelState.IsValid)
        {
            return View("Create");
        }

        using (TravelContext context = new TravelContext())
        {
            TravelPackage travelToCreate = new TravelPackage();
            
            travelToCreate.Title = formData.Title;
            travelToCreate.Description = formData.Description;
            
            if (formData.ImgUrl != null)
            {
                travelToCreate.ImgUrl = formData.ImgUrl;
            }
            else
            {
                travelToCreate.ImgUrl="/img/placeholder.jpg";
            }
            
            travelToCreate.Price = formData.Price;
            travelToCreate.StartDate = formData.StartDate;
            travelToCreate.EndDate = formData.EndDate;

            if (Convert.ToInt32((travelToCreate.EndDate - travelToCreate.StartDate).TotalDays) == 0)
            {
                travelToCreate.Days = 1;
            }
            else
            {
                travelToCreate.Days =
                    Convert.ToInt32((travelToCreate.EndDate - travelToCreate.StartDate).TotalDays);
            }
            
            context.Travels.Add(travelToCreate);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        using (TravelContext context = new TravelContext())
        {
            TravelPackage travelSelected = context.Travels
                .Where(travelPackage => travelPackage.Id == id).First();
            
            if (travelSelected == null)
            {
                return NotFound("Viaggio non trovato");
            }
            
            return View (travelSelected);
        }
        
    }

    [HttpPost]
    public IActionResult Update(int id, TravelPackage formData)
    {
        using (TravelContext context = new TravelContext())
        {
            TravelPackage travelSelected =  context.Travels
                .Where(travelPackage => travelPackage.Id == id).FirstOrDefault();

            travelSelected.Title = formData.Title;
            travelSelected.Description = formData.Description;
            
            if (formData.ImgUrl != null)
            {
                travelSelected.ImgUrl = formData.ImgUrl;
            }
            else
            {
                travelSelected.ImgUrl="/img/placeholder.jpg";
            }
            
            travelSelected.Price = formData.Price;
            travelSelected.StartDate = formData.StartDate;
            travelSelected.EndDate = formData.EndDate;
            
            if (Convert.ToInt32((travelSelected.EndDate - travelSelected.StartDate).TotalDays) == 0)
            {
                travelSelected.Days = 1;
            }
            else
            {
                travelSelected.Days =
                    Convert.ToInt32((travelSelected.EndDate - travelSelected.StartDate).TotalDays);
            }
            
            context.Travels.Update(travelSelected);

            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
        using (TravelContext context = new TravelContext())
        {
            TravelPackage travel =  context.Travels
                .Where(travelPackage => travelPackage.Id == id).FirstOrDefault();
            if (travel == null)
            {
                return NotFound("Non trovato");
            }
            context.Travels.Remove(travel);
            context.SaveChanges();
            return RedirectToAction("Index");
        }   
    }
}

Views/Shared/Partials/_ErrorAuth.cshtml
<div class="container mt-4">

        <div class="card w-100">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>Accesso Negato</h5>
            </div>

            <div class="card-body mx-1 d-flex flex-column flex-md-row row">
                <p>Effettua l'accesso oppure registrati.</p>
            </div>

        </div>
    </div>

Views/Shared/Partials/_Header.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<nav class="navbar navbar-expand-lg navbar_personal">
    <div class="container-fluid">
        <a class="navbar-brand logo" 
           asp-area="" asp-controller="Home" asp-action="Index">
            <span class="block logo-white">
               <svg  x="0px" y="0px" width="134.757px" height="36.698px" viewBox="0 0 134.757 36.698" enable-background="new 0 0 134.757 36.698" xml:space="preserve" class="logo-desktop hidden md:block"><g data-v-025ed5ea="" class="text-road"><path data-v-025ed5ea="" fill="#4D4D4D" d="M51.072,5.007h8.498c1.576,0,3.035,0.21,4.378,0.628c1.342,0.419,2.506,1.034,3.492,1.848
           c0.984,0.813,1.755,1.817,2.309,3.011s0.831,2.568,0.831,4.12c0,1.232-0.173,2.278-0.517,3.14
           c-0.345,0.863-0.727,1.577-1.145,2.143c-0.494,0.641-1.048,1.182-1.662,1.626l5.605,9.72l-1.377,5.455l-5.498-1.388l-7.044-11.904
           v6.244h-7.87L51.072,5.007L51.072,5.007z M58.942,17.126h0.406c0.936,0,1.73-0.209,2.383-0.628
           c0.652-0.419,0.979-1.121,0.979-2.106s-0.327-1.687-0.979-2.106c-0.653-0.419-1.447-0.628-2.383-0.628h-0.406V17.126z"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M69.329,17.329c0-1.773,0.338-3.448,1.016-5.025c0.677-1.576,1.6-2.949,2.771-4.12
           c1.17-1.17,2.543-2.093,4.12-2.771c1.576-0.677,3.251-1.016,5.025-1.016s3.448,0.339,5.025,1.016
           c1.576,0.677,2.949,1.601,4.12,2.771c1.17,1.17,2.093,2.543,2.771,4.12c0.677,1.577,1.016,3.252,1.016,5.025
           c0,1.773-0.339,3.448-1.016,5.025c-0.677,1.577-1.601,2.95-2.771,4.12c-1.171,1.17-2.544,2.094-4.12,2.771
           c-1.577,0.677-3.251,1.016-5.025,1.016s-3.448-0.339-5.025-1.016c-1.577-0.677-2.95-1.601-4.12-2.771
           c-1.171-1.17-2.094-2.543-2.771-4.12C69.667,20.778,69.329,19.102,69.329,17.329z M77.087,17.329c0,0.715,0.135,1.385,0.406,2.014
           c0.27,0.628,0.64,1.176,1.109,1.644c0.468,0.469,1.016,0.838,1.644,1.109c0.628,0.271,1.299,0.407,2.013,0.407
           s1.385-0.135,2.013-0.407c0.628-0.27,1.176-0.64,1.644-1.109c0.468-0.468,0.837-1.016,1.109-1.644
           c0.27-0.628,0.406-1.299,0.406-2.014c0-0.714-0.136-1.385-0.406-2.014c-0.271-0.628-0.641-1.176-1.109-1.644
           c-0.469-0.468-1.016-0.837-1.644-1.109c-0.628-0.27-1.299-0.406-2.013-0.406s-1.385,0.136-2.013,0.406
           c-0.628,0.271-1.177,0.641-1.644,1.109c-0.469,0.469-0.838,1.016-1.109,1.644C77.222,15.944,77.087,16.615,77.087,17.329z"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M99.918,5.007h5.911l9.347,24.644h-7.759l-0.813-2.217h-7.464l-0.813,2.217H90.57L99.918,5.007z
           M104.537,22.003l-1.662-4.323l-1.662,4.323H104.537z"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M113.328,29.651V5.007h6.835c2.315,0,4.378,0.259,6.189,0.776c1.811,0.517,3.337,1.293,4.581,2.328
           c1.243,1.034,2.192,2.322,2.845,3.861c0.652,1.539,0.979,3.32,0.979,5.339c0,2.02-0.327,3.8-0.979,5.339
           c-0.653,1.539-1.601,2.827-2.845,3.861c-1.244,1.034-2.771,1.817-4.581,2.346c-1.811,0.53-3.874,0.795-6.189,0.795H113.328z
           M121.198,22.631c1.848,0,3.275-0.437,4.286-1.312c1.009-0.874,1.515-2.21,1.515-4.009c0-1.798-0.505-3.127-1.515-3.99
           c-1.01-0.862-2.438-1.293-4.286-1.293V22.631z"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M8.058,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M20.36,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M14.209,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M20.36,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M26.511,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M8.058,17.329"></path> <path data-v-025ed5ea="" fill="#4D4D4D" d="M14.209,17.329"></path></g> <g data-v-025ed5ea="" class="text-we"><path data-v-025ed5ea="" fill="#FF4758" d="M31.65,5.007h17.724v6.466H39.52v2.734h6.539v6.133H39.52v2.845h10.112v6.466H31.65V5.007z"></path> <path data-v-025ed5ea="" fill="#FF4758" d="M0,5.007L2.524,0l5.008,2.524l3.664,11.092l2.845-8.608h5.394l2.845,8.608l2.845-8.608h8.35l-8.128,24.643
           h-6.133l-2.475-7.463l-2.476,7.463H8.128L0,5.007z"></path></g>
                 </svg>
             </span>
        </a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa-solid fa-bars"></i>
        </button>
        
        @if (SignInManager.IsSignedIn(User))
        {
           <div class="collapse navbar-collapse navbar_select_container" id="navbarSupportedContent">

               <a id="manage" class="nav-link text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Ciao, @UserManager.GetUserName(User)!</a>
               <a class="nav-link text-white" asp-area="" asp-controller="TravelPackage" asp-action="Index">Gestisci Viaggi</a>
                                   
               <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-white">Esci</button>
                </form>
            </div>
        }
        else
        {
            <div class="collapse navbar-collapse navbar_select_container" id="navbarSupportedContent">

                <a class="nav-link text-white" id="login" asp-area="Identity" asp-page="/Account/Login">Accedi</a>
                <a class="nav-link text-white" id="register" asp-area="Identity" asp-page="/Account/Register">Registrati</a>

            </div>
        }
    </div>
</nav>